### ISSUE TITLE
Create Event "Interactively" instead of "silently"

### ISSUE THREAD

**Issue by elbidone** [meumobi/RImobi#1]
Calendar-PhoneGap-Plugin provides 2 ways to create events: silently or interactively
Interactively allow user to edit details of event before save.
Current version use silent way, we should move it to interactive.
See demo here:
https://github.com/EddyVerbruggen/X-Services-PhoneGap-Build-Plugins-Demo/blob/master/js/calendar-plugin-demo.js

**Comment by t4deu** [comment]
The "interactive" mode is supported only on Android, must check the device platform, if not an android device use the "silently" mode

**Comment by elbidone** [comment]
On service device you implement you should consider the case sensitiveness of device.platform. Then isAndroid if device.platform == "Android" and not android.

On [Cordova Device spec] they provide following examples, please check each you'll use:

> // Depending on the device, a few examples are:
> //   - "Android"
> //   - "BlackBerry 10"
> //   - "iOS"
> //   - "WinCE"
> //   - "Tizen"

[Cordova Device spec]: http://docs.phonegap.com/en/edge/cordova_device_device.md.html

**Comment by t4deu** [comment]
It's already considered:
app/services/device.service.js

```
function platform() {
  return device.platform.toLowerCase();
}
function isAndroid() {
  return this.platform() == 'android';
}
```

**Comment by elbidone** [comment]
then I think it's not intuitive.
Device Service should provide a method to access the original value returned by Cordova. This method obviously should be Device.platform().
If you want to test the platform use the original value there's no need to add a transformation (toLowerCase). So to **be straight forward and coherent with genuine Cordova API**, I recommend:

```js
function platform() {
  return device.platform;
}
function isAndroid() {
  return device.platform == 'Android';
}
```
 
This device Service in future could include for example uniqueDeviceID function and be shared on all our projects
