### ISSUE TITLE
Show placeholder on /files pages of empty

### ISSUE THREAD

**Issue by elbidone** [meumobi/RImobi#13]
see infobox

**Comment by elbidone** [comment]
The behavior is wrong, inconsistent. If you remove the last item, the page remains empty instead of displaying the disclaimer. To test it download a single file, go to /files page and remove it. The disclaimer doesn't appear as expected.

It works well on infoMobi App... as I've explained to you, the Object on view is updated (you respond no but you were wrong), it's why we use a filter.

**Comment by t4deu** [comment]
Fixed, need to generate the apps?
