### ISSUE TITLE
Resync home items after a push notification be received

### ISSUE THREAD

**Issue by t4deu** [meumobi/RImobi#7]

**Comment by elbidone** [comment]
On infoBox we add on run following code

```js
receiveNotification: function() {
	document.addEventListener('push-notification', function(event) {
		$route.reload();
	});
},
```

**Comment by t4deu** [comment]
Don't need to handle for the raw javascript event, the module used on RImobi has this option in the configuration provider:
$pushNotificationProvider.onPushNotification(function(e) {
   $rootScope.$broadcast('reloadData');
});
