### ISSUE TITLE
add sync button and "loading..." flash message on header

### ISSUE THREAD

**Issue by elbidone** [meumobi/RImobi#8]
As done on infoBox, the App IRmobi should provide a sync button on header (left-side of earth icon) to refresh feeds.
When loading, a div should appears with message "Loading.." (pt:"Atualizando...")
The priority is to show it on home. If we can use it also on categories/show better, but this button should not appears on no categories/show pages

**Comment by t4deu** [comment]
Update the request interceptor to trigger the "loading:start" and the "loading:end" events in the requests and responses success and error callbacks.

Create the "loadingMessage" directive, it should observe and handle the "loading:start" and "loading:end" events. each event will set the "scope.isLoading" bollean attribute. The directive template is a "div" with the loading message, that is displayed if the "scope.isLoading" is "true"

add the directive in the IRmobi layout:
```html
....
<body>
<loading-message></loading-message>
<div ng-view></div>
...
```

**Comment by elbidone** [comment]
and what about the sync action ? sync button ? how/where to show/hide button ?

**Comment by t4deu** [comment]
For the sync action we can add a reload method to the $rootScope:
```
$rootScope.reload = function() {
$route.reload();
}
```
Add the button to the navbar, and use a flag configured by the controller to hide or show the button

	<button ng-if="canReload" ng-click="reload()" class="btn btn-primary">
		<i class="fa fa-refresh"></i>
	</button>

**Comment by t4deu** [comment]
to sync the data use the method described [here](http://stackoverflow.com/questions/14693815/how-to-reload-refresh-model-data-from-the-server-programmatically#answers-header), add a wrapper method "loadData" to the Service call and handler.

And to display or hide the button, we can check if the method is set:

<button ng-if="loadData != "undefined"" ng-click="loadData()" class="btn btn-primary">
    <i class="fa fa-refresh"></i>
</button>

**Comment by t4deu** [comment]
Instead show a div with the message, why not add a quote at the side of the reload icon and make the icon spin during the request?

Like this: https://drive.google.com/file/d/0Bws8PHOyYqq9cmlhaVZMWFkwZEk/view?usp=sharing
